---
- name: Test Connectivity and Add Loopback to Routers
  hosts: routers
  gather_facts: no

  tasks:
    - name: Test connection and show version
      ios_command:
        commands: show version
      register: version_output

    - name: Display version summary
      debug:
        msg: "Router {{ inventory_hostname }} version: {{ version_output.stdout_lines[0][0:50] }}"

    - name: Set loopback IP based on host index
      set_fact:
        loopback_ip: "10.0.0.{{ groups['routers'].index(inventory_hostname) + 1 }}"

    - name: Display assigned loopback IP
      debug:
        msg: "{{ inventory_hostname }} will be assigned loopback IP: {{ loopback_ip }}"

    - name: Check if Loopback0 exists
      ios_command:
        commands: show ip interface brief | include Loopback0
      register: lo0_check
      changed_when: false
      failed_when: false

    - name: Configure Loopback0 with unique IP (/32 mask)
      ios_config:
        lines:
          - ip address {{ loopback_ip }} 255.255.255.255
          - no shutdown
        parents: interface Loopback0
        save_when: modified
      register: loopback_config

    - name: Report loopback configuration
      debug:
        msg: "Loopback0 configured on {{ inventory_hostname }} with {{ loopback_ip }}/32"

    - name: Enable OSPF
      ios_config:
        lines:
          - network 10.0.0.0 0.0.0.255 area 0
          - network 192.168.100.0 0.0.0.255 area 0
        parents: router ospf 1
        save_when: modified
      register: ospf_config

    - name: Report OSPF configuration
      debug:
        msg: "OSPF configured on {{ inventory_hostname }}"

    - name: Verify loopback configuration
      ios_command:
        commands: show ip interface brief | include Loopback0
      register: lo0_verify

    - name: Display loopback status
      debug:
        msg: "{{ lo0_verify.stdout_lines }}"
